### ISSUE TITLE
An unknown error has occurred. Please let us know!

### ISSUE THREAD

**Issue by Jake0303** [vimeo/vimeo.js#119]
I am getting an error with the Vimeo API specifically the call of uploading a video (Vimeo API for NodeJS).

```
    2019-10-07 15:21:43.550 ERROR {"error":"An unknown error has occurred. Please let us know!"}
    Error: {"error":"An unknown error has occurred. Please let us know!"}
        at IncomingMessage.<anonymous> (/root/node_modules/vimeo/lib/vimeo.js:164:27)
        at IncomingMessage.emit (events.js:193:15)
        at IncomingMessage.EventEmitter.emit (domain.js:441:20)
        at endReadableNT (_stream_readable.js:1129:12)
        at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

The video is coming from a Zoom livestream, after the livestream is finished we upload it to Vimeo. It worked previously but as of Thursday last week has stopped working.

Manually uploading the video works but obviously I want it to automatically upload.

Here is my code : 
```
var params = {
                        'name': req.body.payload.object.topic,
                        'description': req.body.payload.object.topic,
                        "upload": {
                            "approach": "pull",
                            "size": req.body.payload.object.recording_files[0].file_size,
                            "link": req.body.payload.object.recording_files[0].download_url
                        }
                    };
                    //Edit video title and tags
                    vimeoClient.request({
                        method: 'POST',
                        path: '/me/videos/',
                        query: params
                    }, function (error, body, status_code, headers) {
                        var video = body;
                        if (error) utils.log.error(error);
```

**Comment by nidhi1612** [comment]
hey
I am facing the same issue while interacting with the video using node js. Did you find any solution for the same?
