### ISSUE TITLE
Get all videos in folder

### ISSUE THREAD

**Issue by sangyoo91** [vimeo/vimeo.js#61]
I was wondering if there was a http call that could allow me to get a list of videos within a folder using folder Id.

**Comment by Dashron** [comment]
Folders are not yet supported, but we're working on it!

**Comment by sangyoo91** [comment]
Thats good to hear! I would really benefit from folder features

**Comment by iamgoodbytes** [comment]
Hi, I also need to get my folders and its content through the API. Are there any updates or time estimates on this feature? Thanks!

**Comment by erunion** [comment]
Sorry, we do not yet have an estimate for when folders will be available through the API.

**Comment by ManasMahanand** [comment]
I am getting an error when requesting for videos from folder.
`Error: {"error":"The requested folder couldn't be found."}
    at IncomingMessage.<anonymous> (C:\Users\zigsin\Documents\Projects\dotdotboomWebProjects\ddbnode\node_modules\vimeo\lib\vimeo.js:164:19)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
{"error":"The requested folder couldn't be found."}
`
Here is my code:
`let Vimeo = require('vimeo').Vimeo;
let client = new Vimeo(
  `${vimeoOptions.client_id}`,
  `${vimeoOptions.client_secret}`,
  `${vimeoOptions.access_token}`
);
client.request(
  {
    method: 'GET',
    path: '/users/{my-user-id}/projects/{my-folder-id}/videos',
    query: {
      'sort': 'alphabetical'
    }
  },
  function(error, body, status_code, headers) {
    if (error) {
      console.log(error);
    }

    console.log(body);
  }
);`
I have replaced {my-user-id} and {my-folder-id} with respective ids.

It works on the try it out section from the documentation, I get my videos, but not in my code. Please help!

**Comment by erunion** [comment]
@ManasMahanand Please contact Vimeo support. They'll be able to help you out.

**Comment by ManasMahanand** [comment]
@erunion Thank you, I have submitted a ticket to them.

**Comment by arLevi** [comment]
I'm also experiencing the same issue, what the Vimeo support said ?

**Comment by nitesh098suthar** [comment]
> I'm also experiencing the same issue, what the Vimeo support said ?
> 
> -- edit -- Figured it out, I first debugged it using: Get all the folders that belong to the user: https://developer.vimeo.com/api/reference/folders/3.4#get_projects
> 
> This gave me an error: `Your access token does not have the "private" scope`
> 
> So I generated a new token with public, private scopes
> 
> Then the both endpoints of the API worked for me

------Thanks this worked for me--------
